### PR TITLE
Place configuration file in a project directory

### PR DESCRIPTION
**Pull request by rudi**
- With this change, `rrss2imap` can find its configuration file no matter from
  which directory the user runs it.  Other utilities like `mu` that use a file
  to store persistent configuration do the same.

- If `config.json` is found in the current directory, use it.  This
  maintains backward compatibility for existing users.

- Use the `directories` crate to find a system-appropriate location when
  creating a fresh config file (e.g., `~/.config/rrss2imap/` on Linux).  Read
  the config file from that location unless it’s found in the current directory.

- There is arguably a regression introduced by this change -- after creating a
  new configuration, the user must immediately edit it, and the new location is
  not as convenient as the current directory.  It would be good to add more
  parameters to the `rrss2imap new` subcommand, so that it could generate a
  fully-functional configuration.

### CODE REVIEW

**Comment by rudi** [comment]
Hi, sorry for dropping an unasked-for change here; let me give some background on why I made this patch.  But if you feel that this change goes counter to what you think is the right thing, do feel free to delete the pull request!

I have been using rss2imap for some years, and am happy to switch to rrss2imap, especially since it seems rss2imap might not be ported to python3 any time soon.

While rss2imap is a script, living in the same directory as its config file and state, I'd like to install the rrss2imap binary into `~/.local/bin` or `/usr/local/bin` -- at that point, I might call it from arbitrary directories and it will not find its config.json file.  The `mbsync` program (https://www.djcbsoftware.nl/code/mu/), which does a similar task, keeps its state and configuration in a configurable location, and having `rrss2imap` do the same thing feels right to me.

**Comment by Riduidel** [comment]
Oh my god ! I'm sorry to not seeing your PR earlier!
Thanks A LOT for that.
I fully understand the interest of your PR.
However, your potential regression bothers me a little. can you please elaborate the details of this regression, in order that we find how best to fix it ?

**Comment by Riduidel** [comment]
So, from what I've read, it seems like you'll always create the config file in `~/.config/rrss2imap`.
I would find that acceptable provided

1. We are sure that rrss2imap continue to behave correctly when the config file is in the binary folder
2. There is a message clearly explaining the user here to search for the config file (typically, something like `"config file has been generated in %s"`) would do the job.

What do you think about that ?

**Comment by rudi** [comment]
I agree, a message saying something like "please edit the configuration file in %s." sounds like a good idea.

**Comment by Z01ndels** [comment]
Can you add this message (and solve the merge conflicts that have arisen since I merged some of your other PRs) ? (besides, do you want that I tag your PR as hacktoberfest-accepted ?)

**Comment by Riduidel** [comment]
Can you add this message (and solve the merge conflicts that have arisen since I merged some of your other PRs) ?

**Comment by rudi** [comment]
> Can you add this message (and solve the merge conflicts that have arisen since I merged some of your other PRs) ?

Sure, I'll be happy to.  I have rrss2imap running locally with all changes merged into master, but I submitted independent pull requests so the changes could be reviewed independently.

Btw, there's also the thing where the message date is set to when rrss2imap runs, not when each blog post is written.   I have that fixed locally but it requires a change in the `emailmessage` crate which I haven't submitted upstream yet.

**Comment by Riduidel** [comment]
@rudi Well, setting the feed date as rrss2imap run date bugs me a little: considering that, as of today, feed processing is not immediate, you may loose some items if the feed is the first to be processed and rrss2imap runs for "some" time (for the record, a run on my raspbian lasts 5m27s), which I'm not fond of.
Besides, if you take a look at #43 and #44 these issues may imply that using the date of last message is not even always possible, in which case we should rely upon some other itemd etails (the absolute url, I guess). But let's discuss that in #43

**Comment by rudi** [comment]
> @rudi Well, setting the feed date as rrss2imap run date bugs me a little: considering that, as of today, feed processing is not immediate, you may loose some items if the feed is the first to be processed and rrss2imap runs for "some" time (for the record, a run on my raspbian lasts 5m27s), which I'm not fond of.

I'll try to explain what I mean - in https://github.com/Riduidel/rrss2imap/blob/cfa3ce3573b84ae056daf6b101c905745a86d513/src/message.rs#L87 we set the date of the message that we want to inject into the imap folder.  This date is ignored, and the date + time of the message that shows up in the user's email client is the date+time of when we injected that message.  The reason is that the Rust `emailmessage` crate does not allow us to give the optional `date/time string` argument to t

**Comment by rudi** [comment]
(sorry about closing/reopening the pull request - I fat-fingered something while editing my comment)

**Comment by Riduidel** [comment]
So, what you're saying is that the IMAP message date (and as a consequence the date that will be displayed by mail user agent) is *not* the original date but the date at which the message has been processed ?
Well, let's check that

So I have this tweet https://twitter.com/ruthmalan/status/1314597792904556545 written at `6:05 PM · 9 oct. 2020`. If I look at the imap message, the date header is

     Date: Fri, 09 Oct 2020 16:05:12 GMT

which is in fact the same date, considering I live at GMT+2
It seems like the date is good, no ? I'm sure you're talking about something else, but I don't yet understand what.

**Comment by rudi** [comment]
I merged upstream and print out a message with the path of the config file.  (Also printing a warning when an existing file is left untouched.)

The new function `init_config` might be useful if we decide to add more arguments to `rrss2imap new` besides email - maybe all necessary configuration options could be given as arguments to `rrss2imap new`.

**Comment by rudi** [comment]
> So, what you're saying is that the IMAP message date (and as a consequence the date that will be displayed by mail user agent) is _not_ the original date but the date at which the message has been processed ?

That's what I am observing, yes - but if it's not something you see, it could be down to mail client or imap server differences (I'm on fastmail, I think they use cyrus imapd). I suggest waiting for other users to report this bug - this needs a patch in an upstream crate anyway so I can't submit a pull request.

**Comment by Riduidel** [comment]
Well,
even 47 years old, I have yet to know what "implementation of a spec" 
may involve ... or not.
Do you ahve any possibility to forge messages to send to your IMAP 
server ?
Maybe we should add a "test" command to rrss2imap that would

1. write a message to the IMAP server,
2. ask the user what happen
3. propose to submit a bug report if what he sees doesn"t meet what we 
expect

All that with an issue template that would help us.

What do you think of that ?

**Pull request merged**
